{
    "swagger": "2.0",
    "info": {
        "version": "v2.1",
        "title": "DocuSign Admin API",
        "description": "An API for an organization administrator to manage organizations, accounts and users",
        "contact": {
            "name": "DocuSign Developer Center",
            "url": "https://developers.docusign.com",
            "email": "devcenter@docusign.com"
        },
        "termsOfService": "https://www.docusign.com/company/terms-and-conditions/developers"
    },
    "host": "api.docusign.net",
    "basePath": "/Management",
    "schemes": [
        "https"
    ],
    "paths": {
        "/v2/organizations": {
            "get": {
                "tags": [
                    "Organization"
                ],
                "summary": "Returns a list of organizations that the authenticated user belongs to.",
                "description": "Returns a list of organizations that the authenticated user belongs to.\n\n- Required scopes: `organization_read`.\n\nNote that the DocuSign Admin API only returns JSON, not XML.",
                "operationId": "Organization_Organization_GetListV2",
                "security": [
                    {
                        "accessCode": [
                            "organization_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getOrganizations",
                "x-ds-method": "getOrganizations",
                "x-ds-service": "Accounts",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/accounts/{accountId}/permissions": {
            "get": {
                "tags": [
                    "eSignUserManagement"
                ],
                "summary": "Returns the list of permission profiles in an account.",
                "description": "Returns the list of permission profiles in an account.\n\n- Required scopes: `permission_read`\n\n",
                "operationId": "Account_Accounts_GetPermissionProfilesV2",
                "security": [
                    {
                        "accessCode": [
                            "permission_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getPermissions",
                "x-ds-method": "getPermissions",
                "x-ds-service": "Accounts",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/accounts/{accountId}/groups": {
            "get": {
                "tags": [
                    "eSignUserManagement"
                ],
                "summary": "Returns the list of groups in an account.",
                "description": "Returns the list of groups in an account.\n\n- Required scopes: `group_read`\n",
                "operationId": "Account_Accounts_GetGroupsV2",
                "security": [
                    {
                        "accessCode": [
                            "group_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getGroups",
                "x-ds-method": "getGroups",
                "x-ds-service": "Accounts",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/exports/user_list": {
            "get": {
                "tags": [
                    "UserExport"
                ],
                "summary": "Returns a list of pending and completed export requests.",
                "description": "Returns a list of pending and completed export requests.\n\n- Required scopes: `user_read`\n",
                "operationId": "OrganizationExport_OrganizationExport_Get",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getUserListExports",
                "x-ds-method": "getUserListExports",
                "x-ds-service": "BulkExports",
                "x-ds-in-sdk": true
            },
            "post": {
                "tags": [
                    "UserExport"
                ],
                "summary": "Creates a user list export request.",
                "description": "Create a user list export request.\n\n- Required scopes: `user_read`\n\nThis method initiates a user list export request. You specify the type of export request as JSON in the body of method, like this:\n\n``` json\n{\n\t\"type\": \"organization_memberships_export\"\n}\n```\n\n\n\n\nThe export request type is one of three values:\n\n| Value                                      | Description                                                                           [...]",
                "operationId": "OrganizationExport_OrganizationExport_Insert",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "createUserListExport",
                "x-ds-method": "createUserListExport",
                "x-ds-service": "BulkExports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/exports/account_settings": {
            "get": {
                "tags": [
                    "AccountSettingsExport"
                ],
                "summary": "Returns a list of pending and completed account settings export request.",
                "description": "Returns a list of pending and completed account settings export request.\n\n- Required scopes: `account_read`\n",
                "operationId": "OrganizationExport_OrganizationExport_GetAccountCompare",
                "security": [
                    {
                        "accessCode": [
                            "account_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getAccountSettingsExports",
                "x-ds-method": "getAccountSettingsExports",
                "x-ds-service": "BulkExports",
                "x-ds-in-sdk": true
            },
            "post": {
                "tags": [
                    "AccountSettingsExport"
                ],
                "summary": "Creates a  new account settings export request.",
                "description": "Creates a  new account settings export request.\n\nSpecify the accounts whose settings you are requesting as JSON in the body of method, like this:\n\n``` json\n{\n  \"accounts\":\t[\n  \t{ \"account_id\": \"9ca037f4-xxxx-xxxx-xxxx-212e57d4f22e\"},\n  \t{ \"account_id\": \"624e3e00-xxxx-xxxx-xxxx-43918c520dab\"}\n\n  ]\n}\n```\n",
                "operationId": "OrganizationExport_OrganizationExport_AccountCompare",
                "security": [
                    {
                        "accessCode": [
                            "account_read"
                        ]
                    }
                ],
                "x-ds-methodname": "createAccountSettingsExport",
                "x-ds-method": "createAccountSettingsExport",
                "x-ds-service": "BulkExports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/exports/user_list/{exportId}": {
            "get": {
                "tags": [
                    "UserExport"
                ],
                "summary": "Returns the results for single user list export request.",
                "description": "Returns the results for single user list export request.\n\n- Required scopes: `user_read`\n\nGiven an export id, this method returns the results of a single user list export request.\nTo get a list of all the export requests, use `getUserListExports`.\n\nNote that the `metadata_url` property of the response from `createUserListExport` is a read-to-use HTTP GET request to get the status.\n\nYou can find the actual list of users at  `results[n].url` in the response[...]",
                "operationId": "OrganizationExport_OrganizationExport_GetByExportId",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getUserListExport",
                "x-ds-method": "getUserListExport",
                "x-ds-service": "BulkExports",
                "x-ds-in-sdk": true
            },
            "delete": {
                "tags": [
                    "UserExport"
                ],
                "summary": "Deletes a single user list export request.",
                "description": "Deletes a single user list export request.\nUse this method to delete pending or completed user export requests.\n\n- Required scopes: `user_read`\n\n",
                "operationId": "OrganizationExport_OrganizationExport_DeleteByExportId",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "deleteUserListExport",
                "x-ds-method": "deleteUserListExport",
                "x-ds-service": "BulkExports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/exports/account_settings/{exportId}": {
            "get": {
                "tags": [
                    "AccountSettingsExport"
                ],
                "summary": "Returns the results for a single account settings export request.",
                "description": "Returns the results for a single account settings export request.\n\n- Required scopes: `account_read`\n\nGiven an export id, this method returns the results of an account settings export request.\nTo get a list of all the export requests, use `getAccountSettingsExports`.\n\nYou can find the actual list of settings at  `results[n].url` in the response. The settings export is formatted like this:\n\n``` json\n{\n  \"accounts\": [\n    {\n      \"account_id\": \"9ca[...]",
                "operationId": "OrganizationExport_OrganizationExport_GetAccountSettingsExportByExportId",
                "security": [
                    {
                        "accessCode": [
                            "account_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getAccountSettingsExport",
                "x-ds-method": "getAccountSettingsExport",
                "x-ds-service": "BulkExports",
                "x-ds-in-sdk": true
            },
            "delete": {
                "tags": [
                    "AccountSettingsExport"
                ],
                "summary": "Deletes a single account settings export request.",
                "description": "Deletes a single account settings export request.\nAny data associated with the request is also deleted.\n\n- Required scopes: `account_read`\n\n",
                "operationId": "OrganizationExport_OrganizationExport_DeleteByAccountSettingsExportId",
                "security": [
                    {
                        "accessCode": [
                            "account_read"
                        ]
                    }
                ],
                "x-ds-methodname": "deleteAccountSettingsExport",
                "x-ds-method": "deleteAccountSettingsExport",
                "x-ds-service": "BulkExports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/imports/account_settings": {
            "get": {
                "tags": [
                    "AccountSettingsImport"
                ],
                "summary": "Returns the details and metadata for Bulk Account Settings Import requests in the organization.",
                "description": "Returns the details and metadata for Bulk Account Settings Import requests in the organization.\n\n- Required scopes: `account_read`",
                "operationId": "OrganizationImport_OrganizationImportAccountSettings_Get",
                "security": [
                    {
                        "accessCode": [
                            "account_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getBulkAccountSettingsImports",
                "x-ds-method": "getBulkAccountSettingsImports",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            },
            "post": {
                "tags": [
                    "AccountSettingsImport"
                ],
                "summary": "Creates a new account settings import request.",
                "description": "Creates a new account settings import request.\n\n\n- Required scopes: `account_write`",
                "operationId": "OrganizationImport_OrganizationImportAccountSettings_Post",
                "security": [
                    {
                        "accessCode": [
                            "account_write"
                        ]
                    }
                ],
                "x-ds-methodname": "addBulkAccountSettingsImport",
                "x-ds-method": "addBulkAccountSettingsImport",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/imports/account_settings/{importId}": {
            "get": {
                "tags": [
                    "AccountSettingsImport"
                ],
                "summary": "Returns the details/metadata for a Bulk Account Settings Import request.",
                "description": "Returns the details/metadata for a Bulk Account Settings Import request.\n\nRequired - scopes: `account_read`\n\n\n\nGiven an import ID, this method returns the results of an account settings import request.\nTo get a list of all the import requests, use `getAccountSettingsImports`.\n\n",
                "operationId": "OrganizationImport_OrganizationImportAccountSettings_GetById",
                "security": [
                    {
                        "accessCode": [
                            "account_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getBulkAccountSettingsImport",
                "x-ds-method": "getBulkAccountSettingsImport",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            },
            "delete": {
                "tags": [
                    "AccountSettingsImport"
                ],
                "summary": "Deletes a Bulk Account Settings Import request.",
                "description": "Deletes a single account settings import request.\nAny data associated with the request is also deleted.\n\n- Required scopes: `account_write`",
                "operationId": "OrganizationImport_OrganizationImportAccountSettings_DeleteById",
                "security": [
                    {
                        "accessCode": [
                            "account_write"
                        ]
                    }
                ],
                "x-ds-methodname": "deleteBulkAccountSettingsImport",
                "x-ds-method": "deleteBulkAccountSettingsImport",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/imports/bulk_users/add": {
            "post": {
                "tags": [
                    "UserImport"
                ],
                "summary": "Creates a request to import new users into an account.",
                "description": "Creates a request to import *new* users.\n\n- Required scopes: `user_write`\n\n\n\nYour CSV import file is made up of a header row with the column headers and a row of user or account data for each user you want to add to an account. Only new users can be imported. Any changes to existing users will be ignored. To make changes to existing users, use `updateBulkUserImports`.\n\nTo ensure your CSV is properly formatted, use the\n[Sample Bulk Add CSV file](https://ad[...]",
                "operationId": "OrganizationImport_OrganizationImportUsers_Insert",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "addBulkUserImport",
                "x-ds-method": "addBulkUserImport",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/accounts/{accountId}/imports/bulk_users/add": {
            "post": {
                "tags": [
                    "SingleAccountUserImport"
                ],
                "summary": "Import request for adding user to a single account within the organization.\n",
                "description": "Import request for adding user to a single account within the organization.\nThis method lets you upload user information without requiring an AccountId column.\n\n- Required scopes: `user_write`\n",
                "operationId": "OrganizationImport_OrganizationImportSingleAccountUsers_Insert",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "createBulkImportSingleAccountAddUsersRequest",
                "x-ds-method": "createBulkImportSingleAccountAddUsersRequest",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/imports/bulk_users/update": {
            "post": {
                "tags": [
                    "UserImport"
                ],
                "summary": "Bulk updates information for existing users.",
                "description": "Bulk updates information for existing users.\n\n- Required scopes: `user_write`\n\n\n\nYour CSV import file is made up of a header row with the column headers and a row of user or account data for each user you want to add to an account. Only new users can be imported. Any changes to existing users will be ignored. To make changes to existing users, use `updateBulkUserImports`.\n\n**Update limit**: You can update up to 2,000 users on an account and include up to 5[...]",
                "operationId": "OrganizationImport_OrganizationImportUsers_Update",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "updateBulkUserImports",
                "x-ds-method": "updateBulkUserImports",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/accounts/{accountId}/imports/bulk_users/update": {
            "post": {
                "tags": [
                    "SingleAccountUserImport"
                ],
                "summary": "Import request for updating users for a single account\nwithin the organization.",
                "description": "Import request for updating users for a single account\nwithin the organization.\n\n- Required scopes: `user_write`\n\nThis method lets you upload user information without requiring an AccountId column.\n\n",
                "operationId": "OrganizationImport_OrganizationImportSingleAccountUsers_Update",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "createBulkImportSingleAccountUpdateUsersRequest",
                "x-ds-method": "createBulkImportSingleAccountUpdateUsersRequest",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/imports/bulk_users/close": {
            "post": {
                "tags": [
                    "UserImport"
                ],
                "summary": "Creates a request to close the accounts of existing users.",
                "description": "Creates a request to close the accounts of existing users.\n\n- Required scopes: `user_write`\n\nGiven a CSV list of users, close their accounts.\n\n\nYour CSV import file is made up of a header row with the column headers and a row of user or account data for each user whose account you want to close.\n\nTo ensure your CSV is properly formatted, use the\n[Sample Bulk Update CSV file](https://admin.docusign.com/static-resources/organization-user-update-import.csv)[...]",
                "operationId": "OrganizationImport_OrganizationImportUsers_Close",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "closeBulkUserImportRequest",
                "x-ds-method": "closeBulkUserImportRequest",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/imports/bulk_users/close_external": {
            "post": {
                "tags": [
                    "UserImport"
                ],
                "summary": "Closes external memberships.",
                "description": "Closes external memberships.\n\n- Required scopes: `user_write`\n\nExternal memberships are:\n\n- Users who have an email address at a verified domain\n- But do not belong to the organization\n",
                "operationId": "OrganizationImport_OrganizationImportUsers_CloseExternal",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "closeBulkExternalUserImportRequest",
                "x-ds-method": "closeBulkExternalUserImportRequest",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/imports/bulk_users": {
            "get": {
                "tags": [
                    "UserImport"
                ],
                "summary": "Gets a list of all of the user import requests.",
                "description": "Gets a list of all of the user import requests.\n\n- Required scopes: `user_read`\n",
                "operationId": "OrganizationImport_OrganizationImportUsers_Get",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getBulkUserImportRequests",
                "x-ds-method": "getBulkUserImportRequests",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/imports/bulk_users/{importId}": {
            "get": {
                "tags": [
                    "UserImport"
                ],
                "summary": "Returns the details of a single user import request.",
                "description": "Returns the details of a single user import request.\n\n- Required scopes: `user_read`\n\nUse this method to check the status of the request by looking at the `status` property of the response.\nOnce the status becomes `completed` (or fails), use this method to get the details.\n\nTo get a list of all of the user import requests, use `getBulkUserImportRequests`.",
                "operationId": "OrganizationImport_OrganizationImportUsers_GetById",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getBulkUserImportRequest",
                "x-ds-method": "getBulkUserImportRequest",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            },
            "delete": {
                "tags": [
                    "UserImport"
                ],
                "summary": "Deletes a specific user import request.",
                "description": "Deletes a specific import request and its results.\n\n- Required scopes: `user_write`\n\n\nTo delete a user, see `closeBulkUserImportRequest`.",
                "operationId": "OrganizationImport_OrganizationImportUsers_DeleteById",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "deleteBulkUserImport",
                "x-ds-method": "deleteBulkUserImport",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/imports/bulk_users/{importId}/results_csv": {
            "get": {
                "tags": [
                    "UserImport"
                ],
                "summary": "Given the ID of a user import request,\nreturn the CSV file that was imported.",
                "description": "Returns the contents of the CSV file\nassociated with a user import request.\n\n- Required scopes: `user_read`\n\nThe results have an additional column,\n`ProcessingResults`,\nthat describes the results of importing that row.\n",
                "operationId": "OrganizationImport_OrganizationImportUsers_GetCSVResults",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getBulkUserImportCSV",
                "x-ds-method": "getBulkUserImportCSV",
                "x-ds-service": "BulkImports",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/identity_providers": {
            "get": {
                "tags": [
                    "IdentityProviders"
                ],
                "summary": "Returns the list of identity providers for an organization.",
                "description": "Returns the list of identity providers for an organization.\n\n- Required scopes: `identity_provider_read`\n",
                "operationId": "Organization_GetIdentityProviders",
                "security": [
                    {
                        "accessCode": [
                            "identity_provider_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getIdentityProviders",
                "x-ds-method": "getIdentityProviders",
                "x-ds-service": "IdentityProviders",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/reserved_domains": {
            "get": {
                "tags": [
                    "ReservedDomains"
                ],
                "summary": "Returns the list of reserved domains for the organization.",
                "description": "Returns the list of reserved domains for the organization.\n\n- Required scopes: `domain_read`.\n\nPlease note the DocuSign Admin API only returns JSON, not XML.",
                "operationId": "Organization_GetReservedDomains",
                "security": [
                    {
                        "accessCode": [
                            "domain_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getReservedDomains",
                "x-ds-method": "getReservedDomains",
                "x-ds-service": "ReservedDomains",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/users/profiles": {
            "post": {
                "tags": [
                    "eSignUserManagement"
                ],
                "summary": "Updates a user's information.",
                "description": "Updates a user's information.\n\n- Required scopes: `user_write`\n\n",
                "operationId": "User_Users_UpdateV2",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "updateUser",
                "x-ds-method": "updateUser",
                "x-ds-service": "Users",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/users/email_addresses": {
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "Updates a user's email address.",
                "description": "Updates a user's email address.\n\n- Required scopes: `user_write`\n\n",
                "operationId": "User_Users_UpdateEmailAddressesV2",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "updateEmailAddress",
                "x-ds-method": "updateEmailAddress",
                "x-ds-service": "Users",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/users/{userId}/accounts": {
            "delete": {
                "tags": [
                    "eSignUserManagement"
                ],
                "summary": "Closes a user's memberships.",
                "description": "Closes a user's memberships.\n\n- Required scopes: `user_write`\n\n",
                "operationId": "User_Users_CloseMembershipsV2",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "closeMemberships",
                "x-ds-method": "closeMemberships",
                "x-ds-service": "Users",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/users": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Returns information about the users in an organization.",
                "description": "Returns information about the users in an organization.\n\n\n- Required scopes: `user_read`\n\nYou must include at least one of the following query parameters in the request:\n\n- `account_id`: The id of an account associated with the organization.\n- `organization_reserved_domain_id`: The id of one of the organization's reserved domains.\n- `email`: An email address associated with the users that you want to return.",
                "operationId": "OrganizationUser_OrganizationUsers_GetV2",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getUsers",
                "x-ds-method": "getUsers",
                "x-ds-service": "Users",
                "x-ds-in-sdk": true
            },
            "post": {
                "tags": [
                    "eSignUserManagement"
                ],
                "summary": "Creates a new user.",
                "description": "Creates a new user.\n\n- Required scopes: `user_write`\n\n",
                "operationId": "OrganizationUser_Users_AddV2",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "createUser",
                "x-ds-method": "createUser",
                "x-ds-service": "Users",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/users/{userId}/memberships/{membershipId}": {
            "post": {
                "tags": [
                    "eSignUserManagement"
                ],
                "summary": "Activates user memberships.",
                "description": "Activates user memberships.\n\n- Required scopes: `user_write`\n",
                "operationId": "OrganizationUser_Users_ActivateMembershipV2",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "activateMembership",
                "x-ds-method": "activateMembership",
                "x-ds-service": "Users",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/users/profile": {
            "get": {
                "tags": [
                    "eSignUserManagement"
                ],
                "summary": "Returns information about recently modified users.\n",
                "description": "Returns information about recently modified users.\n\n- Required scopes: `user_read`\n\nThe response includes up to the first 20 users modified\nin the last 10 days.\n\n\n\n\n",
                "operationId": "OrganizationUser_OrganizationUsers_GetProfileV2",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getUserProfiles",
                "x-ds-method": "getUserProfiles",
                "x-ds-service": "Users",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/users/{userId}/identities": {
            "delete": {
                "tags": [
                    "eSignUserManagement"
                ],
                "summary": "Deletes user identities.",
                "description": "Deletes user identities.\n\n- Required scopes: `user_write`\n\n",
                "operationId": "OrganizationUser_DeleteIdentitiesV2",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "deleteIdentities",
                "x-ds-method": "deleteIdentities",
                "x-ds-service": "Users",
                "x-ds-in-sdk": true
            }
        },
        "/v2/organizations/{organizationId}/accounts/{accountId}/users": {
            "post": {
                "tags": [
                    "eSignUserManagement"
                ],
                "summary": "Adds users to an account.",
                "description": "Adds users to an account.\n\n- Required scopes: `user_write`\n\n",
                "operationId": "OrganizationUser_OrganizationUsers_PostAccountUsersV2",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "addUsers",
                "x-ds-method": "addUsers",
                "x-ds-service": "Users",
                "x-ds-in-sdk": true
            }
        },
        "/v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups": {
            "get": {
                "tags": [
                    "MultiProductUserManagement"
                ],
                "summary": "Returns a list of DSGroups.",
                "description": "Returns a list of DSGroups\n\n- Required scopes: `user_read`",
                "operationId": "DocuSignGroupsv21_GetDSGroups_V2_1",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getDSGroups",
                "x-ds-method": "getDSGroups",
                "x-ds-service": "DSGroups",
                "x-ds-in-sdk": true
            },
            "post": {
                "tags": [
                    "MultiProductUserManagement"
                ],
                "summary": "Creates a new DSGroup.",
                "description": "Creates a new DSGroup.\n\n- Required scopes: `user_write`",
                "operationId": "DocuSignGroupsv21_AddDSGroup_V2_1",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "addDSGroup",
                "x-ds-method": "addDSGroup",
                "x-ds-service": "DSGroups",
                "x-ds-in-sdk": true
            }
        },
        "/v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups/{dsGroupId}": {
            "get": {
                "tags": [
                    "MultiProductUserManagement"
                ],
                "summary": "Returns details about a single DSGroup.",
                "description": "Returns details about a single DSGroup.\n\n- Required scopes: `user_read`",
                "operationId": "DocuSignGroupsv21_GetDSGroup_V2_1",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getDSGroup",
                "x-ds-method": "getDSGroup",
                "x-ds-service": "DSGroups",
                "x-ds-in-sdk": true
            },
            "delete": {
                "tags": [
                    "MultiProductUserManagement"
                ],
                "summary": "Deletes a DSGroup.",
                "description": "Deletes a DSGroup\n\n- Required scopes: `user_write`",
                "operationId": "DocuSignGroupsv21_DeleteDSGroup_V2_1",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "deleteDSGroup",
                "x-ds-method": "deleteDSGroup",
                "x-ds-service": "DSGroups",
                "x-ds-in-sdk": true
            }
        },
        "/v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups/{dsGroupId}/users": {
            "get": {
                "tags": [
                    "MultiProductUserManagement"
                ],
                "summary": "Gets a list of users in a DSGroup.",
                "description": "Gets a list of users in a DSGroup.\n\n- Required scopes: `user_read`",
                "operationId": "DocuSignGroupsv21_GetDSGroupUsers_V2_1",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getDSGroupUsers",
                "x-ds-method": "getDSGroupUsers",
                "x-ds-service": "DSGroups",
                "x-ds-in-sdk": true
            },
            "post": {
                "tags": [
                    "MultiProductUserManagement"
                ],
                "summary": "Adds a list of users to a DSGroup.",
                "description": "Adds a list of users to a DSGroup.\n\n- Required scopes: `user_write`",
                "operationId": "DocuSignGroupsv21_AddDSGroupUsers_V2_1",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "addDSGroupUsers",
                "x-ds-method": "addDSGroupUsers",
                "x-ds-service": "DSGroups",
                "x-ds-in-sdk": true
            },
            "delete": {
                "tags": [
                    "MultiProductUserManagement"
                ],
                "summary": "Removes a list of users from a DSGroup.",
                "description": "Removes a list of users from a DSGroup.\n\n- Required scopes: `user_write`",
                "operationId": "DocuSignGroupsv21_RemoveDSGroupUsers_V2_1",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "removeDSGroupUsers",
                "x-ds-method": "removeDSGroupUsers",
                "x-ds-service": "DSGroups",
                "x-ds-in-sdk": true
            }
        },
        "/v2.1/organizations/{organizationId}/accounts/{accountId}/products/permission_profiles": {
            "get": {
                "tags": [
                    "MultiProductUserManagement"
                ],
                "summary": "Gets products associated with the account and the available permission profiles.",
                "description": "Gets products associated with the account and the available permission profiles.\n\n- Required scopes: `user_read`",
                "operationId": "OrganizationProductPermissionProfile_GetProductPermissionProfiles",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getProductPermissionProfiles",
                "x-ds-method": "getProductPermissionProfiles",
                "x-ds-service": "ProductPermissionProfiles",
                "x-ds-in-sdk": true
            }
        },
        "/v2.1/organizations/{organizationId}/accounts/{accountId}/products/users/{userId}/permission_profiles": {
            "get": {
                "tags": [
                    "MultiProductUserManagement"
                ],
                "summary": "Retrieves a list of user's permission profiles for each account's product.",
                "description": "Retrieves a list of user's permission profiles for each account's product.\n\n- Required scopes: `user_read`",
                "operationId": "OrganizationProductPermissionProfile_GetUserProductPermissionProfiles",
                "security": [
                    {
                        "accessCode": [
                            "user_read"
                        ]
                    }
                ],
                "x-ds-methodname": "getUserProductPermissionProfiles",
                "x-ds-method": "getUserProductPermissionProfiles",
                "x-ds-service": "ProductPermissionProfiles",
                "x-ds-in-sdk": true
            },
            "post": {
                "tags": [
                    "MultiProductUserManagement"
                ],
                "summary": "Assigns user to permission profiles for one or more products.",
                "description": "Assigns user to permission profiles for one or more products.\n\n- Required scopes: `user_write`",
                "operationId": "OrganizationProductPermissionProfile_PostUserProductPermissionProfiles",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "addUserProductPermissionProfiles",
                "x-ds-method": "addUserProductPermissionProfiles",
                "x-ds-service": "ProductPermissionProfiles",
                "x-ds-in-sdk": true
            }
        },
        "/v2.1/organizations/{organizationId}/accounts/{accountId}/users": {
            "post": {
                "tags": [
                    "MultiProductUserManagement"
                ],
                "summary": "Creates and updates a multi-product user.",
                "description": "Creates and updates a multi-product user.\n\n- Required scopes: `user_write`",
                "operationId": "OrganizationUser_OrganizationUsers_PostAccountUsersV2_1",
                "security": [
                    {
                        "accessCode": [
                            "user_write"
                        ]
                    }
                ],
                "x-ds-methodname": "addOrUpdateUser",
                "x-ds-method": "addOrUpdateUser",
                "x-ds-service": "Users",
                "x-ds-in-sdk": true
            }
        }
    },
    "securityDefinitions": {
        "accessCode": {
            "type": "oauth2",
            "description": "OAuth2 Access code Grant",
            "flow": "accessCode",
            "authorizationUrl": "https://account.docusign.com/oauth/auth",
            "tokenUrl": "https://account.docusign.com/oauth/auth",
            "scopes": {
                "organization_read": "",
                "permission_read": "",
                "group_read": "",
                "user_read": "",
                "account_read": "",
                "account_write": "",
                "user_write": "",
                "identity_provider_read": "",
                "domain_read": ""
            }
        }
    },
    "tags": [
        {
            "name": "Users",
            "description": "Methods to manage users in an account."
        },
        {
            "name": "eSignUserManagement",
            "description": "Methods to manage eSignature users in an account."
        },
        {
            "name": "MultiProductUserManagement",
            "description": "Methods to manage multi-product users in an account."
        },
        {
            "name": "UserExport",
            "description": "Methods for exporting a user list."
        },
        {
            "name": "AccountSettingsExport",
            "description": "Methods and objects to get account information."
        },
        {
            "name": "UserImport",
            "description": "Methods to import users.\n\nTo ensure your CSV is properly formatted, use the\n[Sample Bulk Add CSV file](https://admin.docusign.com/static-resources/organization-user-import.csv)\n as a template.\n\nYou can add up to 2,000 users to an account and include up to 50 accounts per import. The maximum number of users per import is 8,000."
        },
        {
            "name": "IdentityProviders",
            "description": "Methods to get a list of identity providers."
        },
        {
            "name": "ReservedDomains",
            "description": "Methods to get a list of reserved domains."
        },
        {
            "name": "Organization",
            "description": "Methods for working with organizations."
        },
        {
            "name": "AccountSettingsImport",
            "description": "Methods and objects to update account settings."
        },
        {
            "name": "SingleAccountUserImport",
            "description": "Methods to import users."
        }
    ],
    "x-ds-categories": [
        {
            "name": "UserManagement",
            "summary": "Methods to manage users in an account.",
            "description": "Methods to manage users in an account."
        },
        {
            "name": "BulkOperations",
            "summary": "Methods to import and export users and accounts.",
            "description": "Methods to import and export users and accounts."
        },
        {
            "name": "IdentityProviders",
            "summary": "Methods to get a list of identity providers.",
            "description": "Methods to get a list of identity providers."
        },
        {
            "name": "ReservedDomains",
            "summary": "Methods to get a list of reserved domains.",
            "description": "Methods to get a list of reserved domains."
        },
        {
            "name": "Organization",
            "summary": "Methods for working with organizations.",
            "description": "Methods for working with organizations."
        }
    ]
}